### ISSUE TITLE
patternMarkers 'all' returning empty lists

### ISSUE THREAD

**Issue by kwoyshner** [FertigLab/CoGAPS#102]
Hi! I am trying to obtain patternMarkers from a cogaps result object using the following code:
pMarks <- patternMarkers(NMF, threshold = "all", lp = NA, axis = 1)

It returns values for the scores and ranks how I would expect, but there are no patternMarkers for **every** pattern -- which seems weird.
<img width="345" alt="image" src="https://github.com/FertigLab/CoGAPS/assets/45450805/30cdb3fd-1426-4f7b-8777-c39053dfc83e">
<img width="597" alt="image" src="https://github.com/FertigLab/CoGAPS/assets/45450805/5248e721-df91-4d47-8ee9-16fe57ec0ff7">

The 'cut' version does return patternMarkers, but the output is formatted slightly differently than that returned by 'all' (each list isn't named by the pattern name), and there is a warning message I haven't seen before when using this function.
<img width="621" alt="image" src="https://github.com/FertigLab/CoGAPS/assets/45450805/537fd40f-3a15-4b56-93d2-af85ddb02f58">
<img width="673" alt="image" src="https://github.com/FertigLab/CoGAPS/assets/45450805/14bf8575-1163-41a2-884c-e2433445a495">

I am using R 4.3.0 and CoGAPS 3.24.0 (installed 5/2/24).
I have never run into this issue before, but I had just reinstalled CoGAPS.

Looking into the patternMarkers code here (lines 480-490):
![image](https://github.com/FertigLab/CoGAPS/assets/45450805/8f42d8d5-0148-4a65-9195-3366e75da001)
If I print the first few elements of thresholdTest it looks like a named list, but if I print the gene followed by names(gene) for each, the names are NULL
<img width="662" alt="image" src="https://github.com/FertigLab/CoGAPS/assets/45450805/a42bf0aa-4bc0-4aa3-860c-66c3dfdf35ca">

I'm not sure if this is happening for anyone else. Please let me know if you need any other details!

**Comment by dimalvovs** [comment]
related https://github.com/FertigLab/CoGAPS/pull/78

**Comment by dimalvovs** [comment]
confirmed warning in `threshold = "cut"`

```
test_that("patternMarkers work with threshold = 'cut' yields no warning", {
    #set up
    data(GIST)
    res <- CoGAPS(GIST.data_frame, nIterations=1000,
                  seed=1, messages=FALSE)

    test <- patternMarkers(res, threshold = "cut")
    expect_no_warning(length(test$PatternMarkers), 0)
})
```

**Comment by dimalvovs** [comment]
confirmed empty markers with `threshold = 'all'`
```
test_that("patternMarkers work with threshold = 'all' for general mode", {
    #set up
    data(GIST)
    res <- CoGAPS(GIST.data_frame, nIterations=1000,
                  seed=1, messages=FALSE)

    test <- patternMarkers(res, threshold = "all")
    marker_lengths <- sapply(test$PatternMarkers, length)
    expect_equal(sum(marker_lengths > 0), length(marker_lengths))
})
```

**Comment by dimalvovs** [comment]
the problem with warnings generated in case of `threshold='cut'` comes from the non-matching dimensions of As and Ps during the scaling and `sweep`ing . For the testdata, the dimensions of A and P that are fed into here https://github.com/FertigLab/CoGAPS/blob/cc8c42cd2a9dc9c99e63e22dba076fabfdb8461e/R/methods-CogapsResult.R#L437 are: 
```
[1] 1363    7
[1] 9 7
```
