### ISSUE TITLE
Seeking Clarification on Functions in the CoGAPS Package

### ISSUE THREAD

**Issue by mumdark** [FertigLab/CoGAPS#114]
Thank you for your excellent work. I noticed that this R package includes other functions such as scCoGAPS and GWCoGAPS, which are not mentioned in the vignette. What are the differences between these and CoGAPS?

Thanks for your help!

**Comment by dimalvovs** [comment]
Hey, thanks, those should probably be not exported anymore as [ having been deprecated](https://github.com/FertigLab/CoGAPS/blob/5a8f4cc2768289a1f5c7290cd39a77e607c3c88f/R/CoGAPS.R#L177). To learn more about running CoGAPS with single-cell or genome-wide mode, refer to the[ vignette section](https://bioconductor.org/packages/release/bioc/vignettes/CoGAPS/inst/doc/CoGAPS.html#single-cell-cogaps).

**Comment by dimalvovs** [comment]
closing as answered.
