### ISSUE TITLE
Remove boost dependency for distribution functions

### ISSUE THREAD

**Issue by sherman5** [FertigLab/CoGAPS#13]
This has caused a few headaches in the past and in general seems to be vulnerable to errors based on architecture/compile flags.

**Comment by sherman5** [comment]
A lookup table might provide a nice solution here. It will simultaneously remove the boost dependency and provide a performance increase.

**Comment by ejfertig** [comment]
I’m concerned writing this ourselves would introduce more bugs than if will fix.

**Comment by genesofeve** [comment]
I'm all for any performance boosts we can get.

**Comment by sherman5** [comment]
This wouldn't give any performance boost, so nothing lost there.

**Comment by sherman5** [comment]
@ejfertig What do you think about including the headers we need from boost in the package src folder? I believe I've seen other packages do this, and it would at least remove the dependency on which version of boost the user has installed

**Comment by sherman5** [comment]
I created this issue because I ran into this error: https://svn.boost.org/trac10/ticket/10005 when trying to run cogaps in valgrind
