### ISSUE TITLE
Issue with NA values in dataset when running CoGAPS

### ISSUE THREAD

**Issue by mperezrodriguez** [FertigLab/CoGAPS#134]
Hello,
this is my first time running CoGAPS and I'm encountering an error related to NA values in my datase. Below is the script I used:
```markdown
library(CoGAPS)
data = readRDS(file = "Data/my_data.R")
params <- new("CogapsParams")
params <- setParam(params, "sparseOptimization", TRUE)
cogapsresult <- CoGAPS(data, params, outputFrequency = 10000) 
```
I obtain the following parameters:
```markdown
> params
-- Standard Parameters --
nPatterns            7 
nIterations          50000 
seed                 148 
sparseOptimization   TRUE 

-- Sparsity Parameters --
alpha          0.01 
maxGibbsMass   100 
```
Hoever, I encounter the following error:
```markdown
> cogapsresult <- CoGAPS(data, params, outputFrequency = 10000) 
Error in checkDataMatrix(data, uncertainty, allParams$gaps) : 
  NA values in data
```
I'm using CoGAPS version 3.27.2., and I made sure there are no genes in the dataset where all values are NA. I also tried modifying nPatters or even running without modifying the sparseOptimization parameter, but the error persists.

Additionally, I also tried to create a different params object using the following code, but another error arises:
```markdown
params <- CogapsParams(nPatterns = 5, nIterations = 50000, seed = 123, distributed = "genome-wide", sparseOptimization = TRUE)
params <- setDistributedParams(params, nSets = 5)
```
Here is the error I receive:
```markdown
> cogapsresult <- CoGAPS(data, params, outputFrequency = 10000) 
Error in checkDataMatrix(data, uncertainty, allParams$gaps) : 
  NA values in data
Además: Warning message:
In checkInputs(data, uncertainty, allParams) :
  running distributed cogaps without mtx/tsv/csv/gct data
```
My dataset is a data.frame. I also tried using it as a matrix, but the error was the same.

I hope you can help me with this issue. Please let me know if you need any additional information or if there's anything I should adjust is my script.

Thank you so much in advance!

**Comment by dimalvovs** [comment]
thanks for posting @mperezrodriguez! are there any NA cells in your dataset?

**Comment by mperezrodriguez** [comment]
Thank you for your reply, @dimalvovs. Yes, there's many NA cells in our dataset.

**Comment by dimalvovs** [comment]
I think NAs are not allowed in the dataset, do the NAs represent sparsity? If so, could the NAs be 0s instead?

**Comment by mperezrodriguez** [comment]
I replaced the NAs with 0s. Now it works.
Thanks!

**Comment by dimalvovs** [comment]
great, happy it worked!
