### ISSUE TITLE
Re-Write Vignettes

### ISSUE THREAD

**Issue by sherman5** [FertigLab/CoGAPS#32]
Instead of a single, monolithic vignette, it is more useful to have multiple vignettes that focus on different user objectives with CoGAPS. Some ideas:

- Data Input
- Configuring Parameters
- Running over multiple values for nPatterns
- Cell Type Identification with Pattern Markers
- Gene Set Statistics

Branch: revamp_vignettes

**Comment by dimalvovs** [comment]
@sherman5 it looks like vignette has been reworked in 3dfda03 so I am closing this issues for the moment!
