### ISSUE TITLE
Linking to Rhdf5lib

### ISSUE THREAD

**Issue by grimbough** [FertigLab/CoGAPS#35]
Apologies for breaking your package by changing the returned value of Rhdf5lib::pkg_config().

It looks like you've removed the dependency on this, and based on a cursory look can't see where you need it, so the is probably the simplest solution.  However, if you do need to link against Rhdf5lib you can update the entry in `src/Makevars` to be:

```
    RHDF5_LIBS=$(shell echo 'Rhdf5lib::pkgconfig("PKG_CXX_LIBS")'|\
        "${R_HOME}/bin/R" --vanilla --slave)  
    PKG_LIBS=$(RHDF5_LIBS)
```

I've reverted the change in BioC release, so no need to worry about fixing that before the deadline.  Apologies again for do this at such a crappy time.

**Comment by dimalvovs** [comment]
It has been some time, but - thanks!
