### ISSUE TITLE
less pattern numbers than 'nPatterns'

### ISSUE THREAD

**Issue by qingnanl** [FertigLab/CoGAPS#52]
Dear developers,

Thanks for the cool package you designed. I tried to follow the 'cogaps for seurat objects' tutorial. One thing seems confusing is that the pattern numbers I found were less than the 'nPatterns' I set. Is that normal or I missed anything?

Another question is what normalization is best for running CoGAPS for single-cell data?

Thanks!

**Comment by lothm2014** [comment]
Thank you for your interest in CoGAPS. It is normal for the results to contain a different number of patterns than what was specified for the ‘nPatterns’ parameter. CoGAPS subsets cells from the input data matrix and infers the latent spaces within the subsets. The final amplitude and pattern matrices are formulated using consensus patterns found across the subset results where the number of consensus patterns is not necessarily equal to the 'nPatterns' parameter. 

When running CoGAPS on single cell data, it is recommended to remove genes that have a variance equal to zero and to log-transform the counts matrix.

**Comment by qingnanl** [comment]
> Thank you for your interest in CoGAPS. It is normal for the results to contain a different number of patterns than what was specified for the ‘nPatterns’ parameter. CoGAPS subsets cells from the input data matrix and infers the latent spaces within the subsets. The final amplitude and pattern matrices are formulated using consensus patterns found across the subset results where the number of consensus patterns is not necessarily equal to the 'nPatterns' parameter.
> 
> When running CoGAPS on single cell data, it is recommended to remove genes that have a variance equal to zero and to log-transform the counts matrix.

Thanks for the suggestions!
