### ISSUE TITLE
RNASeq Data Preprocessing for CoGAPS

### ISSUE THREAD

**Issue by mdmanurung** [FertigLab/CoGAPS#54]
Hello,

I recently came across this package and am really interested to try it out. However, I am not entirely sure what should I do to preprocess my RNA-Seq data before inputting to CoGAPS. Would you mind listing the necessary steps? I tried using rlog-transformed count matrix, which I have used for WGCNA, but then I got an error saying that the algorithm does not accept negative values. 

Thank you in advance.

Best,
Mikhael

**Comment by lothm2014** [comment]
Hi Mikhael,

The following are the recommended minimum preprocessing steps:

1. Remove the cells with no signal.
2. Remove the genes with no signal or constant signal.
3. Add one to all values and log transform the data. This will help avoid the negative values. 

Please reach out if you have additional questions and thank you for your interest in CoGAPS. 

Sincerely,
Melanie
