### ISSUE TITLE
RunCoGAPS on Seurat object

### ISSUE THREAD

**Issue by YuliaInn** [FertigLab/CoGAPS#61]
Hello,

I found the idea of finding patterns and projecting them into similar datasets very promising in such a challenging part of scRNA-seq analysis as cell identification. I am trying to annotate my own data using CoGAPS and I found [this tutorial](https://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/cogaps.html) that shows how to run CoGAPS on Seurat objects. The function that was used there is called `RunCoGAPS`, but I can't find it in the package documentation. I have several questions about that function:
1. does it use all genes or only highly variable ones?
2. which data slot does it use? normalized I guess?
3. will the cell embeddings from RunCoGAPS be similar to the result of scCoGAPS on a scRNA-seq normalized count matrix?

thank you,
Yulia

**Comment by ejfertig** [comment]
Elana J. Fertig, PhD
Director of the Quantitative Sciences Division
co-Director Convergence Institute
Associate Cancer Center Director of Quantitative Sciences
Daniel Nathans Scientific Innovator
Associate Professor of Oncology, Biomedical Engineering, and Applied Mathematics and Statistics
Johns Hopkins University
https://fertiglab.com
@FertigLab

On Jan 14, 2022, at 10:52 AM, YuliaInn ***@***.******@***.***>> wrote:



Hello,

I found the idea of finding patterns and projecting them into similar datasets very promising in such a challenging part of scRNA-seq analysis as cell identification. I am trying to annotate my own data using CoGAPS and I found this tutorial<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhtmlpreview.github.io%2F%3Fhttps%3A%2F%2Fgithub.com%2Fsatijalab%2Fseurat-wrappers%2Fblob%2Fmaster%2Fdocs%2Fcogaps.html&data=04%7C01%7Cejfertig%40jhmi.edu%7C894877db0a8c4850bc2108d9d775d20c%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637777723314348656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l2j%2BOJdG2eQy%2FVFBov6g4q3jgrCf4%2F2KFLRAZyrsYYA%3D&reserved=0> that shows how to run CoGAPS on Seurat objects. The function that was used there is called RunCoGAPS, but I can't find it in the package documentation. I have several questions about that function:

  1.  does it use all genes or only highly variable ones?

You can select either. Using all genes will increase run time but provide more information. Genes selected need to have non-zero variance for the algorithm to work.


  1.  which data slot does it use? normalized I guess?

Correct, normalized data.


  1.  will the cell embeddings from RunCoGAPS be similar to the result of scCoGAPS on a scRNA-seq normalized count matrix?

They should be identical.


thank you,
Yulia

**Comment by YuliaInn** [comment]
thank you very much for your prompt reply
