### ISSUE TITLE
nPattern value selection

### ISSUE THREAD

**Issue by davemcg** [FertigLab/CoGAPS#64]
I'm not certain what to set nPattern at (in `params` for `CoGAPS::CoGAPS()`. Is there any harm (besides run time??) at setting a large value for this? Then potentially prune patterns with "low" amplitudes?

**Comment by ejfertig** [comment]
nPattern determines the dimensionality of the factorization. We recommend running across a range of dimensions and assessing robustness of the solutions for analysis of biological systems.

**Comment by davemcg** [comment]
Ah, OK, that is very helpful thanks.
