### ISSUE TITLE
CoGAPS on proteomic data

### ISSUE THREAD

**Issue by dm8000** [FertigLab/CoGAPS#65]
Hello
Is CoGAPS usable on proteomic data?

**Comment by ejfertig** [comment]
Yes! Please see this paper https://jitc.bmj.com/content/jitc/8/2/e000932.full.pdf and we have an accepted manuscript using CoGAPS on CyTOF by Sidiropoulos et al which is in press as well.

**Comment by dm8000** [comment]
Nice, thank you!
