### ISSUE TITLE
result interpretation

### ISSUE THREAD

**Issue by dm8000** [FertigLab/CoGAPS#66]
Hello

I ran the vignette but I have some troubles on interpreting the results.

1. The rows in the example matrix have a prefix _Hs._ followed by a number.  Is this a gene annotation?

2. If I understood correctly, would the patterns be groups of correlated features? If so, where can I find which feature belongs to which pattern? I was not able to find it in the _result_ object.

**Comment by dimalvovs** [comment]
It's been some time, but still:
1. _Hs_ symbols correspond to the Unigene names, which still can be mapped to other names, for example [Hs.93485](https://www.ncbi.nlm.nih.gov/gene/?term=Hs.93485%5BUniGene+Cluster+Number%5D)
2. Features in patterns are not necessarily correlated, features x patterns matrix can be obtained by calling `res@featureLoadings` on the resulting CoGAPS object.
